language: r

sudo: required

r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

env:
  matrix:
  - JAGS='--configure-args="--with-jags"'
  - JAGS=""
  global:
    - OS=$(uname -s)


r_check_args: --as-cran --install-args="$JAGS"

apt_packages:
  - jags

brew_packages:
  - jags

r_packages:
  - RcppEigen
  - TMB
  - inline
  - rjags


script:
  - make check
  - make install
  - make test


after_success:
  - cat multiStockassessment.Rcheck/00check.log
  - cat multiStockassessment.Rcheck/00install.out

after_failure:
  - cat multiStockassessment.Rcheck/00check.log
  - cat multiStockassessment.Rcheck/00install.out
