language: c

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

matrix:
  - env: JAGS=FALSE
  - env: JAGS=TRUE

env:
  global:
    - OS=$(uname -s)

sudo: required

before_install:
  - if test ${OS} = Darwin; then curl -O http://r.research.att.com/libs/gfortran-4.8.2-darwin13.tar.bz2; fi
  - if test ${OS} = Darwin; then sudo tar fvxz gfortran-4.8.2-darwin13.tar.bz2 -C /; fi
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - if test ${OS} = Darwin; then if test ${JAGS} = TRUE; then brew install jags; fi fi
  - if test ! ${OS} = Darwin; then if test ${JAGS} = TRUE; then apt-get install jags; fi fi
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh install_r rjags
  - ./travis-tool.sh install_r TMB

script: ./travis-tool.sh run_tests

on_failure:
  - ./travis-tool.sh dump_logs
  - less /Users/travis/build/calbertsen/covafillr/covafillr.Rcheck/00check.log
  - less /Users/travis/build/calbertsen/covafillr/covafillr.Rcheck/00install.out