language: r

sudo: required

r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

env:
  matrix:
  - JAGS='--configure-args="--with-jags"'
  - JAGS=""
  global:
    - OS=$(uname -s)


r_check_args: --as-cran --install-args="$JAGS"

install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install jags; else brew install jags; fi
  - R -e 'install.packages(c("roxygen2","RcppEigen","TMB","inline","rjags"),dependencies = c("Depends", "Imports", "LinkingTo", "Enhances"))'

script:
  - make check
  - make install
  - make test


after_success:
  - cat covafillr.Rcheck/00check.log
  - cat covafillr.Rcheck/00install.out

after_failure:
  - cat covafillr.Rcheck/00check.log
  - cat covafillr.Rcheck/00install.out
